  postTicket:
      Type: AWS::Serverless::Function
      Properties:
        Handler: src/interface/handlers/post-ticket.handler
        Runtime: nodejs12.x
        MemorySize: 128
        Timeout: 100
        Description: creates an new Ticket.
        Policies:
          - AWSLambdaExecute
          - DynamoDBCrudPolicy:
              TableName: Ticket
        Environment:
          Variables:
            LOG_LEVEL: DEBUG
            TICKET_TABLE_NAME: Ticket
        Events:
          Api:
            Type: Api
            Properties:
              Path: /Ticket
              Method: POST
