  postReseller:
      Type: AWS::Serverless::Function
      Properties:
        Handler: src/interface/handlers/post-reseller.handler
        Runtime: nodejs12.x
        MemorySize: 128
        Timeout: 100
        Description: creates an new Reseller.
        Policies:
          - AWSLambdaExecute
          - DynamoDBCrudPolicy:
              TableName: Reseller
        Environment:
          Variables:
            LOG_LEVEL: DEBUG
            AGENT_TABLE_NAME: Reseller
        Events:
          Api:
            Type: Api
            Properties:
              Path: /Reseller/
              Method: POST
