  Resselers:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ResselerId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  Tikets:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "ResselerId"
            AttributeType: "S"
          - AttributeName: "tiketCode"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "ResselerId"
            KeyType: "HASH"
          - AttributeName: "tiketCode"
            KeyType: "RANGE"

  PreApproved:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: cpf
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
