  Resselers:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "ResselerId"
          AttributeType: "S"
        - AttributeName: "email"
          AttributeType: "S"
        - AttributeName: "cpf"
          AttributeType: "S"
      KeySchema:
        AttributeName: ResselerId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: "Reseller"
      GlobalSecondaryIndexes:
        - IndexName: "byLogin"
          KeySchema:
            - AttributeName: "email"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
        - IndexName: "byCpf"
          KeySchema:
            - AttributeName: "cpf"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL


  Tickets:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "cpf"
            AttributeType: "S"
          - AttributeName: "code"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "cpf"
            KeyType: "HASH"
          - AttributeName: "code"
            KeyType: "RANGE"
        TableName: "Reseller"
