  postLogin:
      Type: AWS::Serverless::Function
      Properties:
        Handler: src/interface/handlers/post-login.handler
        Runtime: nodejs12.x
        MemorySize: 128
        Timeout: 100
        Description: validate reseller login.
        Policies:
          - AWSLambdaExecute
          - DynamoDBCrudPolicy:
              TableName: Reseller
        Environment:
          Variables:
            LOG_LEVEL: DEBUG
            RESELLER_TABLE_NAME: Reseller
        Events:
          Api:
            Type: Api
            Properties:
              Path: /login
              Method: POST
